export const mockDriverLoads = [
  {
    id: 'LOAD001',
    from: 'Mumbai',
    to: 'Pune',
    distance: '148 km',
    weight: '15 tons',
    goodsType: 'Electronics',
    price: '₹8,500',
    timeEstimate: '4-5 hours',
    tag: 'Return Trip Assured',
    isOptimal: true,
  },
  {
    id: 'LOAD002',
    from: 'Mumbai',
    to: 'Nashik',
    distance: '180 km',
    weight: '20 tons',
    goodsType: 'Textiles',
    price: '₹10,200',
    timeEstimate: '5-6 hours',
    tag: 'Premium',
    isOptimal: false,
  },
  {
    id: 'LOAD003',
    from: 'Navi Mumbai',
    to: 'Pune',
    distance: '155 km',
    weight: '18 tons',
    goodsType: 'Machinery',
    price: '₹9,800',
    timeEstimate: '4-5 hours',
    tag: 'Near Me',
    isOptimal: false,
  },
  {
    id: 'LOAD004',
    from: 'Thane',
    to: 'Aurangabad',
    distance: '340 km',
    weight: '22 tons',
    goodsType: 'Iron & Steel',
    price: '₹16,500',
    timeEstimate: '8-9 hours',
    tag: 'Long Distance',
    isOptimal: false,
  },
  {
    id: 'LOAD005',
    from: 'Panvel',
    to: 'Belgaum',
    distance: '380 km',
    weight: '25 tons',
    goodsType: 'Cement',
    price: '₹18,200',
    timeEstimate: '9-10 hours',
    tag: 'Premium',
    isOptimal: false,
  },
]

export const mockShipperLoads = [
  {
    id: 'SL001',
    from: 'Mumbai Port',
    to: 'Pune Distribution',
    weight: '15 tons',
    price: '₹8,500',
    status: 'Pending',
    postedAt: '2 hours ago',
  },
  {
    id: 'SL002',
    from: 'Nashik Factory',
    to: 'Delhi Hub',
    weight: '22 tons',
    price: '₹24,500',
    status: 'In Transit',
    postedAt: '8 hours ago',
  },
  {
    id: 'SL003',
    from: 'Bangalore Warehouse',
    to: 'Hyderabad Center',
    weight: '18 tons',
    price: '₹12,300',
    status: 'Delivered',
    postedAt: '1 day ago',
  },
  {
    id: 'SL004',
    from: 'Chennai Port',
    to: 'Kolkata Hub',
    weight: '30 tons',
    price: '₹35,800',
    status: 'Pending',
    postedAt: '3 hours ago',
  },
]

export const locations = [
  'Mumbai',
  'Pune',
  'Nashik',
  'Thane',
  'Navi Mumbai',
  'Panvel',
  'Delhi',
  'Bangalore',
  'Hyderabad',
  'Chennai',
  'Kolkata',
  'Aurangabad',
  'Belgaum',
]

export const goodsTypes = [
  'Electronics',
  'Textiles',
  'Machinery',
  'Iron & Steel',
  'Cement',
  'Agriculture',
  'Chemicals',
  'Pharmaceuticals',
  'FMCG',
  'Auto Parts',
]

export const mockUserProfile = {
  name: 'Raj Kumar',
  phone: '+91 9876543210',
  language: 'English',
  role: 'driver',
}
